 git remote set-url origin git@github.com:cpausmit/MitCommon
 git remote set-url origin git@github.com:cpausmit/MitAna
 git remote set-url origin git@github.com:cpausmit/MitProd
 git remote set-url origin git@github.com:cpausmit/MitEdm
 git remote set-url origin git@github.com:cpausmit/MitPlots
 git remote set-url origin git@github.com:cpausmit/Config
 git remote set-url origin git@github.com:cpausmit/PausHaus
 git remote set-url origin git@github.com:cpausmit/IntelROCCS
 git remote set-url origin git@github.com:cpausmit/DynamicData
